### ISSUE TITLE
Fails to authenticate...

### ISSUE THREAD

**Issue by ashif-ismail** [suyashbansal/Way2SMS-API-1#2]
@suyashbansal this script doesnt work,it fails to authenticate as it was in the parent repo...it just throws "invalid login"

**Comment by ashif-ismail** [comment]
Check my Working Repo at https://github.com/SheikhZayed/WAY2SMS-API.git,
Try the sample app : http://ancient-lowlands-31895.herokuapp.com/

**Comment by suyashbansal** [comment]
I do not understand why this is not working for you. I am myself using it on 2 projects.
Give me more details about the method you are using.
