### ISSUE TITLE
Not Working since 10.05.2017

### ISSUE THREAD

**Issue by cpl2015** [suyashbansal/Way2SMS-API-1#4]
Since 10th May 2017, this API is not working. It shows 'invalid login'. Please fix. Thank You.

**Comment by suyashbansal** [comment]
Sure. I'll have a look.

**Comment by suyashbansal** [comment]
This issue was moved to suyashbansal/Way2SMS-API-1#2

**Comment by suyashbansal** [comment]
Check the updated code here : https://github.com/suyashbansal/Way2SMS-API
